import Phaser from 'phaser';
import { careerState } from '../state/careerState.js';

const COLORS={bg:0x0b0e12,panel:0x151a21,panel2:0x1c222b,panel3:0x11161c,border:0x2a323d,text:0xf4f6f8,muted:0x8d97a3,accent:0xe53935,accentHover:0xff4f4a,gold:0xffcf52,green:0x5bc47b,blue:0x5b9cff};
function hex(v){return `#${v.toString(16).padStart(6,'0')}`;}
export class HubScene extends Phaser.Scene{
  constructor(){super('HubScene');}
  create(){
    console.log('REGISTERED SCENES:', this.scene.manager.keys);
    this.cameras.main.setBackgroundColor(hex(COLORS.bg));this.drawBackground();this.drawHeader();this.drawProfileCard();this.drawNextEventCard();this.drawQuickStats();this.drawBottomNav();this.drawRecentResult();this.input.keyboard.on('keydown-ENTER',()=>this.scene.start('RaceMenuScene'));}
  drawBackground(){const g=this.add.graphics();g.fillStyle(0x151a21,1);g.fillCircle(790,90,260);g.fillStyle(0x0b0e12,1);g.fillCircle(790,90,190);const grid=this.add.graphics();grid.lineStyle(1,0x171c23,.55);for(let x=0;x<=960;x+=40)grid.lineBetween(x,0,x,690);for(let y=0;y<=690;y+=40)grid.lineBetween(0,y,960,y);}
  drawHeader(){this.add.text(40,30,'RACING LIFE',{fontFamily:'Arial',fontSize:34,fontStyle:'bold',color:hex(COLORS.text)});this.add.text(42,73,'CAREER HUB',{fontFamily:'Arial',fontSize:13,fontStyle:'bold',color:hex(COLORS.accent)});this.add.text(700,34,`SEASON ${careerState.season}`,{fontFamily:'Arial',fontSize:15,fontStyle:'bold',color:hex(COLORS.text)}).setOrigin(1,0);this.add.text(700,58,`WEEK ${careerState.week}`,{fontFamily:'Arial',fontSize:14,color:hex(COLORS.muted)}).setOrigin(1,0);this.add.rectangle(720,86,200,1,COLORS.border);this.add.text(700,97,`CASH  $${careerState.money.toLocaleString()}`,{fontFamily:'Arial',fontSize:16,fontStyle:'bold',color:hex(COLORS.gold)}).setOrigin(1,0);}
  drawProfileCard(){const x=40,y=125,w=420,h=235;this.panel(x,y,w,h);this.add.rectangle(x+30,y+28,130,175,COLORS.panel3).setOrigin(0);this.add.rectangle(x+93,y+62,62,62,0x313944);this.add.circle(x+124,y+84,26,0x8f9aa7);this.add.rectangle(x+86,y+113,76,66,0x6e7783);this.add.triangle(x+124,y+42,x+100,y+68,x+148,y+68,COLORS.accent);this.add.text(x+95,y+185,'RACER',{fontFamily:'Arial',fontSize:11,fontStyle:'bold',color:hex(COLORS.muted)}).setOrigin(.5,0);this.add.text(x+188,y+28,careerState.racerName.toUpperCase(),{fontFamily:'Arial',fontSize:28,fontStyle:'bold',color:hex(COLORS.text)});this.add.text(x+188,y+64,'ROOKIE RACER',{fontFamily:'Arial',fontSize:13,fontStyle:'bold',color:hex(COLORS.accent)});this.add.text(x+188,y+102,'TEAM',{fontFamily:'Arial',fontSize:11,fontStyle:'bold',color:hex(COLORS.muted)});this.add.text(x+188,y+121,careerState.team.toUpperCase(),{fontFamily:'Arial',fontSize:16,fontStyle:'bold',color:hex(COLORS.text)});this.metricRow(x+188,y+157,'MANAGER TRUST',careerState.trust,COLORS.blue);this.metricRow(x+188,y+194,'REPUTATION',careerState.reputation,COLORS.gold);}
  metricRow(x,y,label,value,color){this.add.text(x,y,label,{fontFamily:'Arial',fontSize:10,fontStyle:'bold',color:hex(COLORS.muted)});this.add.text(x+218,y-2,`${value}`,{fontFamily:'Arial',fontSize:13,fontStyle:'bold',color:hex(COLORS.text)}).setOrigin(1,0);this.add.rectangle(x,y+19,218,6,COLORS.panel3).setOrigin(0);this.add.rectangle(x,y+19,218*(value/100),6,color).setOrigin(0);}
  drawNextEventCard(){const x=480,y=125,w=440,h=235;this.panel(x,y,w,h);this.add.text(x+24,y+22,'NEXT EVENT',{fontFamily:'Arial',fontSize:12,fontStyle:'bold',color:hex(COLORS.muted)});this.add.text(x+24,y+50,'CHAMPIONSHIP RACE',{fontFamily:'Arial',fontSize:24,fontStyle:'bold',color:hex(COLORS.text)});this.add.text(x+24,y+88,'CHOOSE YOUR TRACK',{fontFamily:'Arial',fontSize:15,fontStyle:'bold',color:hex(COLORS.accent)});this.add.text(x+24,y+112,'5 racers  •  3 laps  •  Multiple circuits',{fontFamily:'Arial',fontSize:13,color:hex(COLORS.muted)});this.add.text(x+24,y+148,'OBJECTIVE',{fontFamily:'Arial',fontSize:10,fontStyle:'bold',color:hex(COLORS.muted)});this.add.text(x+24,y+166,'Pick a map, then line up against four AI racers.',{fontFamily:'Arial',fontSize:13,color:hex(COLORS.text)});this.actionButton(x+258,y+166,156,44,'▶  PLAY',()=>this.scene.start('RaceMenuScene'));}
  drawQuickStats(){const x=40,y=380,w=880,h=122;this.panel(x,y,w,h);this.add.text(x+22,y+18,'CAREER SNAPSHOT',{fontFamily:'Arial',fontSize:12,fontStyle:'bold',color:hex(COLORS.muted)});[['TRUST',`${careerState.trust}/100`,COLORS.blue],['REPUTATION',`${careerState.reputation}/100`,COLORS.gold],['RACE ENTRIES',`${careerState.raceHistory.length}`,COLORS.green],['TEAM STATUS','ACTIVE',COLORS.accent]].forEach((c,i)=>{const cx=x+22+i*213;this.add.rectangle(cx,y+48,198,56,COLORS.panel3).setOrigin(0);this.add.rectangle(cx,y+48,4,56,c[2]).setOrigin(0);this.add.text(cx+14,y+58,c[0],{fontFamily:'Arial',fontSize:10,fontStyle:'bold',color:hex(COLORS.muted)});this.add.text(cx+14,y+77,c[1],{fontFamily:'Arial',fontSize:17,fontStyle:'bold',color:hex(COLORS.text)});});}
  drawBottomNav(){const items=[{label:'CAREER',active:true},{label:'GARAGE',scene:'GarageScene'},{label:'TEAM'},{label:'WORLD'},{label:'PROFILE'}];const y=525,totalW=880,startX=40,gap=8,itemW=(totalW-gap*(items.length-1))/items.length;items.forEach((item,i)=>{const x=startX+i*(itemW+gap),bg=item.active?COLORS.accent:COLORS.panel2,textColor=item.active?COLORS.text:COLORS.muted,nav=this.add.rectangle(x,y,itemW,43,bg).setOrigin(0);this.add.text(x+itemW/2,y+21,item.label,{fontFamily:'Arial',fontSize:11,fontStyle:'bold',color:hex(textColor)}).setOrigin(.5);nav.setInteractive({useHandCursor:!item.active});if(!item.active){nav.on('pointerover',()=>nav.setFillStyle(COLORS.border));nav.on('pointerout',()=>nav.setFillStyle(COLORS.panel2));nav.on('pointerdown',()=>{if(item.scene)this.scene.start(item.scene);});}});}
  drawRecentResult(){const last=careerState.raceHistory[careerState.raceHistory.length-1];if(!last){this.add.text(40,590,'No race history yet. Your first result will appear here.',{fontFamily:'Arial',fontSize:13,color:hex(COLORS.muted)});return;}const result=last.finished?`LAST RESULT  •  Week ${last.week}  •  Finished all ${last.totalLaps} laps`: `LAST RESULT  •  Week ${last.week}  •  DNF after ${last.lapsCompleted}/${last.totalLaps} laps`;this.add.text(40,590,result,{fontFamily:'Arial',fontSize:12,color:hex(last.finished?COLORS.green:COLORS.accent)});}
  panel(x,y,w,h){const g=this.add.graphics();g.fillStyle(COLORS.panel,1);g.fillRoundedRect(x,y,w,h,16);g.lineStyle(1,COLORS.border,1);g.strokeRoundedRect(x,y,w,h,16);return g;}
  actionButton(x,y,w,h,label,callback){const bg=this.add.rectangle(x,y,w,h,COLORS.accent).setOrigin(0).setDepth(10);this.add.text(x+w/2,y+h/2,label,{fontFamily:'Arial',fontSize:12,fontStyle:'bold',color:hex(COLORS.text)}).setOrigin(.5).setDepth(11);bg.setInteractive({useHandCursor:true});bg.on('pointerover',()=>bg.setFillStyle(COLORS.accentHover));bg.on('pointerout',()=>bg.setFillStyle(COLORS.accent));bg.on('pointerdown',callback);return bg;}
}
